import type { AppState, ThemeConfig, ThemeName } from './types'

export const THEMES: Record<ThemeName, ThemeConfig> = {
  default: {
    name: 'default',
    label: 'Delamain',
    accentBlue: '#7eb8da',
    accentGreen: '#7ec8a0',
    accentPink: '#f4a0b0',
    accentPurple: '#b8a0e8',
    primary: '#7eb8da',
  },
  rose: {
    name: 'rose',
    label: 'Rose',
    accentBlue: '#f0a0b8',
    accentGreen: '#f0c8a0',
    accentPink: '#e87878',
    accentPurple: '#d8a0d0',
    primary: '#f0a0b8',
  },
  mint: {
    name: 'mint',
    label: 'Mint',
    accentBlue: '#78d8b8',
    accentGreen: '#a0e8a0',
    accentPink: '#b8e8c8',
    accentPurple: '#88d0c0',
    primary: '#78d8b8',
  },
  lavender: {
    name: 'lavender',
    label: 'Lavender',
    accentBlue: '#c0a8f0',
    accentGreen: '#a8c0e8',
    accentPink: '#e0b8f0',
    accentPurple: '#d0a8e8',
    primary: '#c0a8f0',
  },
  peach: {
    name: 'peach',
    label: 'Peach',
    accentBlue: '#f0c890',
    accentGreen: '#d8e890',
    accentPink: '#f0a878',
    accentPurple: '#e8b0a0',
    primary: '#f0c890',
  },
  sky: {
    name: 'sky',
    label: 'Sky',
    accentBlue: '#90d0f0',
    accentGreen: '#90e8d8',
    accentPink: '#a8c8f0',
    accentPurple: '#b0d0e8',
    primary: '#90d0f0',
  },
  mauve: {
    name: 'mauve',
    label: 'Mauve',
    accentBlue: '#c8a8d8',
    accentGreen: '#a8c8b8',
    accentPink: '#e0b0c8',
    accentPurple: '#d0b8e0',
    primary: '#c8a8d8',
  },
}

export const INITIAL_STATE: AppState = {
  activeConversationId: 'conv-1',
  leftSidebarOpen: true,
  rightPanel: null,
  blankSlate: false,
  incognito: false,
  sensitive: false,
  sensitiveUnlocked: false,
  model: 'github_copilot/gpt-5.4-mini',
  defaultModel: 'github_copilot/gpt-5.4-mini',
  budgetUsed: 47,
  budgetTotal: 300,
  contextMode: 'Normal',
  theme: 'default',
  titleGeneration: true,
  systemContext: `You are Delamain, Daniel's personal AI assistant.\nYou have access to his vault, notes, calendar events, and remote machines.\nBe concise, direct, and precise. Prefer structured output when appropriate.`,
  shortTermContinuity: `Last active project: refactor auth middleware\nPending: quarterly taxes, research proposal draft\nActive model routes: github_copilot/gpt-5.4-mini (default), claude-haiku-4.5 for cheap fallback`,
  settingsTab: 'settings' as const,
  contextFiles: [
    { id: 'f1', name: 'Timeline.md', path: 'Vault/Notes/Timeline.md', bytes: 1420, tokenEstimate: 340 },
    { id: 'f2', name: 'system-context.md', path: 'Vault/Config/system-context.md', bytes: 880, tokenEstimate: 210 },
  ],
  tools: [
    { id: 't1', name: 'read_text_file', description: 'Read a file from the vault', enabled: true, category: 'read' },
    { id: 't2', name: 'write_text_file', description: 'Write or update a vault file', enabled: true, category: 'write' },
    { id: 't3', name: 'search_vault', description: 'Full-text search across vault notes', enabled: true, category: 'read' },
    { id: 't4', name: 'ssh_winpc', description: 'Run shell commands on winpc via SSH', enabled: true, category: 'ssh' },
    { id: 't5', name: 'ssh_serrano', description: 'Run shell commands on serrano via SSH', enabled: true, category: 'ssh' },
    { id: 't6', name: 'web_search', description: 'Search the web for current information', enabled: false, category: 'web' },
  ],
  healthEntries: [
    { id: 'h1', label: 'backend', status: 'ok', detail: 'API responding', lastChecked: '12s ago' },
    { id: 'h2', label: 'helpers', status: 'ok', detail: 'All helpers healthy', lastChecked: '12s ago' },
    { id: 'h3', label: 'serrano SSH', status: 'ok', detail: 'Reachable', lastChecked: '1m ago' },
    { id: 'h4', label: 'winpc SSH', status: 'ok', detail: 'Reachable', lastChecked: '1m ago' },
    { id: 'h5', label: 'Syncthing', status: 'degraded', detail: '2 devices out of sync', lastChecked: '2m ago' },
    { id: 'h6', label: 'Copilot Budget', status: 'ok', detail: '47 / 300 tokens used', lastChecked: '12s ago' },
    { id: 'h7', label: 'Models', status: 'unknown', detail: 'Endpoint not yet live', lastChecked: 'never' },
    { id: 'h8', label: 'Vault Index', status: 'ok', detail: '1,204 notes indexed', lastChecked: '5m ago' },
  ],
  directActions: [
    { id: 'da1', group: 'health', label: 'health.backend', description: 'Check backend health', status: 'idle' },
    { id: 'da2', group: 'health', label: 'health.helpers', description: 'Check helper health', status: 'idle' },
    { id: 'da3', group: 'ref', label: 'ref.status', description: 'Reference index status', status: 'idle' },
    { id: 'da4', group: 'ref', label: 'ref.reconcile_dry_run', description: 'Dry-run reference reconciliation', status: 'idle' },
    { id: 'da5', group: 'vault_index', label: 'vault_index.status', description: 'Vault index status', status: 'idle' },
    { id: 'da6', group: 'vault_index', label: 'vault_index.build', description: 'Rebuild vault index', status: 'idle' },
    { id: 'da7', group: 'sync_guard', label: 'sync_guard.status', description: 'Syncthing guard status', status: 'idle' },
    { id: 'da8', group: 'winpc', label: 'winpc.hostname', description: 'Get winpc hostname', status: 'idle' },
    { id: 'da9', group: 'winpc', label: 'winpc.date', description: 'Get winpc date/time', status: 'idle' },
  ],
  workers: [
    {
      id: 'w1',
      name: 'Codex — refactor-auth',
      type: 'codex',
      host: 'local',
      status: 'running',
      startedAt: '14m ago',
      lastActivity: '2s ago',
      output: 'Analyzing middleware chain...\nRefactored 3 of 7 files.',
    },
    {
      id: 'w2',
      name: 'serrano tmux',
      type: 'tmux',
      host: 'serrano',
      status: 'idle',
      startedAt: '2h ago',
      lastActivity: '45m ago',
    },
  ],
  conversations: [
    {
      id: 'conv-1',
      title: "What's due this week?",
      timestamp: '2h ago',
      active: true,
      runStatus: 'completed',
      messages: [
        {
          id: 'm1',
          role: 'user',
          content: "What's due this week? Check my timeline and any upcoming deadlines.",
          toolCallsBefore: [],
        },
        {
          id: 'm2',
          role: 'assistant',
          content: `## This Week's Deadlines

| Date | Item | Source |
|------|------|--------|
| Apr 18 | Submit draft — research proposal | Timeline.md |
| Apr 19 | Review PR #142 (refactor branch) | Projects/Dev.md |
| Apr 21 | Pay quarterly estimated taxes | Vault/Finance/2026.md |

The research proposal draft is the most time-sensitive item — it was flagged as *high priority* in your timeline note. The [[Projects/Dev]] note also mentions that PR #142 has been sitting for over a week and is blocking the staging deploy.`,
          toolCallsBefore: [
            {
              id: 'tc1',
              name: 'read_text_file',
              summary: 'Read `Vault/Notes/Timeline.md`',
              durationMs: 120,
              status: 'success',
              accentColor: 'blue',
              expanded: true,
              args: { path: 'Vault/Notes/Timeline.md' },
              stdout: `# Timeline — April 2026\n\n## This Week\n- [HIGH] Apr 18 — Submit draft research proposal (faculty review)\n- Apr 19 — Review PR #142\n- Apr 21 — Estimated tax payment due\n\n## Next Week\n- Apr 25 — Dentist appointment 10:00\n- Apr 28 — Team sync (postponed from last week)`,
            },
            {
              id: 'tc2',
              name: 'search_vault',
              summary: "Searched for 'deadline' in Vault/Projects/",
              durationMs: 340,
              status: 'success',
              accentColor: 'blue',
              expanded: false,
              args: { query: 'deadline', path: 'Vault/Projects/' },
              stdout: '3 matches found across 2 files.',
            },
          ],
        },
      ],
    },
    {
      id: 'conv-2',
      title: 'GPU status on winpc',
      timestamp: '45m ago',
      runStatus: 'running',
      messages: [
        {
          id: 'm3',
          role: 'user',
          content: 'Check GPU status on winpc',
          toolCallsBefore: [],
        },
        {
          id: 'm4',
          role: 'assistant',
          content: 'Running `nvidia-smi` now',
          streaming: true,
          toolCallsBefore: [
            {
              id: 'tc3',
              name: 'ssh_winpc',
              summary: 'Running `nvidia-smi` on winpc',
              status: 'running',
              accentColor: 'pink',
              expanded: false,
              args: { host: 'winpc', command: 'nvidia-smi' },
            },
          ],
        },
      ],
    },
    {
      id: 'conv-3',
      title: 'Refactor auth middleware',
      timestamp: 'Yesterday',
      messages: [],
    },
    {
      id: 'conv-4',
      title: 'Meal plan for next week',
      timestamp: 'Apr 14',
      messages: [],
    },
    {
      id: 'conv-5',
      title: 'Research paper summary',
      timestamp: 'Apr 12',
      messages: [],
    },
  ],
}
